### ISSUE TITLE
After reboot, nothing happens

### ISSUE THREAD

**Issue by wcraft** [adafruit/Adafruit-Pi-ExternalRoot-Helper#11]
I went through the instructions on Adafruit, and everything works after the script runs. /mnt/etc/fstab and /boot/cdmline.txt both look good. However, after I reboot, /mnt/ is empty and df -h shows that root is on the SD card. mount | grep displays nothing and readlink dev/root also displays nothing. 

Any suggestions on what I might be doing incorrectly?

**Comment by PvdBerg1998** [comment]
I have the same issue.

**Comment by PvdBerg1998** [comment]
@wcraft It seems `/boot/cmdline.txt` does not get updated. You can edit it manually, then it will work.

**Comment by PvdBerg1998** [comment]
Why is this closed?

**Comment by mathiaslindahl** [comment]
I have the same problem.

@wcraft checked the /boot/cmdline.txt and this is how it looks:
![image](https://user-images.githubusercontent.com/18162403/34600039-e2d1f732-f1f5-11e7-8602-7c2431142103.png)

what should I change?
